#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
# actions for nethserver-p3scan-update event
#--------------------------------------------------

my $event = "nethserver-p3scan-update";
templates2events("/etc/p3scan/p3scan.conf", $event);
templates2events("/etc/init/p3scan.conf", $event);
templates2events("/etc/mail/spamassassin/bwlist.cf", $event);
templates2events("/etc/mail/spamassassin/p3scan.cf", $event);
event_services($event, qw(
   p3scan restart
));
event_actions($event, 'initialize-default-databases' => '00');
event_actions($event, 'firewall-adjust' => '20');

#--------------------------------------------------
# actions for nethserver-mail-filter-save event
#--------------------------------------------------

templates2events("/etc/mail/spamassassin/bwlist.cf", "nethserver-mail-filter-save");
templates2events("/etc/mail/spamassassin/p3scan.cf", "nethserver-mail-filter-save");
